### ISSUE TITLE
Small interface fixes

### ISSUE THREAD

**Issue by Federico77z** [Laniakea-elixir-it/elixir-italy-science-gateway#2]
1) The explanations box is light blue and the fonts are of a slightly darker blue. Adjust colors to make it more readable.
2)Bottom disclaimer should be: "Deployment time may vary depending on the state and load of repositories. Also, the disclaimer should be on top and not at the bottom of the page.
3)Colors of the Galaxy flavours / virtual hardware boxes at the bottom of the page should be adjusted according to the general light tone of the page.

**Comment by mtangaro** [comment]
Bottom disclaimer and Colors updated

**Comment by mtangaro** [comment]
Fixed on Laniakea v2.0.0 with new Dashboard
